### ISSUE TITLE
Is it possible to use this in a CI/CD pipeline?

### ISSUE THREAD

**Issue by rc8marcelo** [jack-r-warren/remove_from_coverage#15]
Hi, I've been trying to integrate `remove_from_coverage` into our GitLab pipeline but I'm not sure if it's supported or if I'm just doing something wrong. I tried looking around and found some StackOverflow questions about it but so far I haven't seen anyone post about actually using this in a pipeline with an implementation so I was wondering if it was possible? I have the following setup below but whenever I try running the remove from coverage command, I don't think it gets triggered because the html generated still has `.g.dart` files.

On my pubspec.yaml file, I have this entry under `dev_dependencies`: `remove_from_coverage: ^2.0.0`

```yaml
unit-test-coverage:
  stage: coverage
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/cirrusci/flutter:2.5.3
  script:
    - flutter pub get
    - flutter pub run build_runner build --delete-conflicting-outputs
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - lcov --remove coverage/lcov.info "lib/src/resources/assets/*" "lib/src/dev_utils/*"
    - flutter pub run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$', '\.freezed\.dart$', '\.config\.dart$' 
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
      - coverage
  interruptible: true
```

**Comment by furaiev** [comment]
Looks like the wrong mask.
try `flutter pub run remove_from_coverage -f coverage/lcov.info -r '.g.dart|.freezed.dart|\bconfig\b'`

**Comment by rc8marcelo** [comment]
I tried this as well as just using `.g.dart` to rule out if it was the regex but it still didn't work

**Comment by furaiev** [comment]
did you try all your commands locally?

**Comment by rc8marcelo** [comment]
I did now and I found out what broke it. Thanks for asking that, I wouldn't have noticed it if I hadn't. It was the `lcov_cleaned.info` that was generating the html and I didn't notice immediately that I was running the remove coverage command on just `lcov.info`

My final CI script ended up like this:
```yaml
unit-test-coverage:
  stage: coverage
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/cirrusci/flutter:2.5.3
  script:
    - flutter pub get
    - flutter pub run build_runner build --delete-conflicting-outputs
    - flutter test --coverage ./lib
    - flutter pub run remove_from_coverage -f coverage/lcov.info -r '.g.dart'
    - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
      - coverage
  interruptible: true
```

I removed the lcov commands because I found alternate solutions for them using the `// coverage:ignore-file` comments and I removed the `.freezed.dart` from the options because the generated code of freezed classes already have the same comment to ignore the file. 

Closing issue.
